### ISSUE TITLE
Unable to customize video element

### ISSUE THREAD

**Issue by prosperoking** [cloudinary/cloudinary-react#131] opened 2019-11-26 16:16 UTC
I am unable to apply customization to the video component created like from this url: https://studio.cloudinary.com/

**Comment by d-mendoza** [comment] 2019-11-27 00:47
Can you provide details on what customizations you are trying to add? Please share samples so we can reproduce on our end too.

**Comment by prosperoking** [comment] 2019-12-03 17:12
Here is a sample code https://stackblitz.com/edit/react-eccg8e

**Comment by maoznir** [comment] 2019-12-03 19:33
Hi @prosperoking,
The React SDK's Video component wraps a regular <video> html element, not the Cloudinary Video Player.  If you'd like to use Cloudinary Video Player in your react Component, you could do something like this:

```
// Video component that wraps Cloudinary Video Player

import React, { Component } from 'react';
import cloudinary from 'cloudinary-core';
import cloudinaryVideoPlayer from 'cloudinary-video-player';
import "cloudinary-video-player/dist/cld-video-player.css";

export default class Video extends Component {
  componentDidMount() {
    const {videoElementId, cloud_name, public_id, width, playerOptions, sourceOptions} = this.props;

    const cloudinaryCore = new cloudinary.Cloudinary({cloud_name});
    const player = cloudinaryCore.videoPlayer(videoElementId, playerOptions);
    player.width(width);
    player.source(public_id, sourceOptions);
  }

  render() {
    const {videoElementId, videoElementOptions} = this.props;
    return (
      <video
        id={videoElementId}
        {...videoElementOptions}
      />
    );
  }
}
~~~
```

**Comment by maoznir** [comment] 2020-02-23 14:33
Closing due to time elapsed.

**Closed by maoznir** 2020-02-23 14:33 UTC
Labels: question
