### ISSUE TITLE
Video component does not work with thumbnail generation

### ISSUE THREAD

**Issue by mattjennings** [cloudinary/cloudinary-react#85] opened 2019-04-05 00:40 UTC
Following the [React Example](https://cloudinary.com/documentation/video_manipulation_and_delivery#generating_video_thumbnails), using a `Video` component with a `publicId` of `someVideoId.jpg` does not turn the Video component into an Image like the docs suggest.

I've created a [codesandbox](https://codesandbox.io/s/pmmq5n9nzm) example to demonstrate the issue.

**Comment by d-mendoza** [comment] 2019-04-05 22:54
Thank you for reporting this and I will pass this along to our dev team.
In the meantime, you can use an Image component and specify the resource_type as "video".

import { Video, Image } from "cloudinary-react";
. . .
<Image cloudName="demo" publicId="dog.jpg" resourceType="video" />
OR
<Image cloudName="demo" publicId="dog" format="jpg" resourceType="video" />

This should generate the image thumbnail.

**Comment by mattjennings** [comment] 2019-04-05 23:06
Thanks!

**Comment by d-mendoza** [comment] 2019-04-16 16:22
@mattjennings 
After reviewing this more thoroughly, the html5 video player tag automatically includes a poster image, so this is not a bug. Although it is not shown expliclity, you can show it this way:

`<Video poster="https://res.cloudinary.com/demo/video/upload/dog.jpg" cloudName="demo" publicId="dog.jpg" resourceType="video" />`

Let me know if this is clear.

**Comment by mattjennings** [comment] 2019-04-16 17:50
Unfortunately that doesn't _quite_ do what I was expecting from the documentation. 

The poster would be for the `video` element that gets rendered, but the documentation page suggests this is how you would get the `<Video />` component to render an `img` element with a generated thumbnail. If you inspect the preview from that documentation page, it is indeed an `img` element, but in my example it remains a `video` element. Effectively, there's no difference when specifying `dog` and `dog.jpg` as the publicId for a `<Video />` component.

**Comment by d-mendoza** [comment] 2019-04-18 19:54
If the desired result is to just have a poster image without any video, I would suggest using the previous method of having `<Image cloudName="demo" publicId="dog.jpg" resourceType="video" />` . I will also communicate to our docs team to clarify this portion of the documentation. We appreciate the feedback.

**Comment by roeeba** [comment] 2020-02-17 10:49
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2020-02-17 10:49 UTC
Labels: bug
