### ISSUE TITLE
Performance issue with list of Image components

### ISSUE THREAD

**Issue by rshackleton** [cloudinary/cloudinary-react#67] opened 2018-09-13 14:53 UTC
Using the following:

```
react@^16.5.0
react-dom@^16.5.0
cloudinary-react@^1.0.6
```

I'm experiencing a significant performance issue when causing a re-render of a list of product cards containing Image components.

![image](https://user-images.githubusercontent.com/13448395/45496278-f89a1a80-b76c-11e8-8b94-f14593f097df.png)

The `componentWillReceiveProps` lifecycle event is taking around 170ms per Image component.

Looks to be related to a recursive loop where something is being cloned:

![image](https://user-images.githubusercontent.com/13448395/45496490-7c540700-b76d-11e8-88ba-4136c47f3185.png)

Sounds like it could be related to the issue raised here which was apparently resolved:
https://github.com/cloudinary/cloudinary-react/issues/31#issuecomment-349079998

**Comment by strausr** [comment] 2018-09-17 12:04
Do you have a live example that you can share with us where this is occurring?

**Comment by aditimadan-Cloudinary** [comment] 2018-11-12 18:46
@davidfrtala as @strausr mentioned it will be great if you could share an example or a link where this issue can be reproduced.

**Comment by strausr** [comment] 2019-01-07 16:32
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by strausr** 2019-01-07 16:32 UTC
Labels: question
