### ISSUE TITLE
Images look blurry on a retina display

### ISSUE THREAD

**Issue by paschaldev** [cloudinary/cloudinary-react#54] opened 2018-05-21 10:26 UTC
I added the `dpr="auto"` but no luck still. 

```jsx
<Image publicId={item.meta.image_id} style={{height: '60px'}}>
     <Transformation dpr="auto" effect="grayscale" height="60" crop="scale" />
</Image>
```

I even used the `cloudinary` package to generate a URL for background images with `dpr` flag but it doesn't render nicely on retina displays.

```js
cloudinary.url(props.cloud_image_id, { dpr: 'auto', height: 700, width: 2000, crop: "fill", background: "#000000", effect: "colorize:24"})
```

However, if I set the `dpr="3.0"`, it works. Any solution or workaround for automatic display detection?

**Comment by strausr** [comment] 2018-05-21 11:52
@paschaldev Can you please share with us the image you're using?

Can you please try removing the extra styling from the Image tag? 


```
<Image publicId={item.meta.image_id}>
     <Transformation dpr="auto" effect="grayscale" height="60" crop="scale" />
</Image>
```

**Comment by paschaldev** [comment] 2018-05-21 14:05
I have removed the extra styling, nothing changed. The reason why I added the extra styling was beacuse if I set `dpr=3.0`, the image grows bigger than the container so I had to make it the same height as the image which renders sharply on the retina screen. 

Full url of the image: `http://res.cloudinary.com/rovyl/image/upload/b_rgb:000000,c_fill,dpr_3.0,e_colorize:24,h_700,w_2000/v1/zyombo/african-3387292`

Public ID: `zyombo/african-3387292`

**Comment by strausr** [comment] 2018-05-22 09:38
@paschaldev Unfortunately, we're unable to reproduce the blurriness you mentioned. Is there a live page we can take a look at?

If you set the image as `responsive` you get the DPR calculation. Regarding dpr=“auto” it needs client hints to work (otherwise the backend doesn’t know which image DPR to return).

**Comment by paschaldev** [comment] 2018-05-22 13:53
Doing this doesn't work 

```js 
cloudinary.url(props.cloud_image_id, { responsive: true, dpr: 'auto', height: 700, width: 2000, crop: "fill", background: "#000000", effect: "colorize:24"})
```

Here is the link to the live app. 

https://zyombo-app.herokuapp.com

**Comment by strausr** [comment] 2018-05-24 09:34
When I run your request 
`cloudinary.url(props.cloud_image_id, { responsive: true, dpr: 'auto', height: 700, width: 2000, crop: "fill", background: "#000000", effect: "colorize:24"})`

I get the following URL which has dpr_auto http://res.cloudinary.com/rovyl/image/upload/b_rgb:000000,c_fill,dpr_auto,e_colorize:24,h_700,w_2000/zyombo/african-3387292

If you would like us to take a closer look, please share with us your project.

Regarding our Image tag, you can use the following

```
<Image 
    cloudName="rovyl"
    publicId='zyombo/african-3387292'
    responsive
    dpr="auto"
    height= "700"
    width= "2000"
    crop= "fill"
/>
```

**Comment by strausr** [comment] 2019-01-07 16:30
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by strausr** 2019-01-07 16:30 UTC
Labels: question
