### ISSUE TITLE
Cannot read property 'opener' of null

### ISSUE THREAD

**Issue by AdamTyler** [cloudinary/cloudinary-react#89] opened 2019-04-24 16:37 UTC
Seeing the above error come up in the file cloudinary-core.js

```
5808   // IE throws on elements created in popups
5809   // FF meanwhile throws on frame elements through "defaultView.getComputedStyle"
5810   if (elem.ownerDocument.defaultView.opener) {
5811     return elem.ownerDocument.defaultView.getComputedStyle(elem, null);
5812   }
```

Seems like the majority of users experiencing these bugs are on Samsung browser on Android

**Comment by d-mendoza** [comment] 2019-04-26 22:26
Hi @AdamTyler 

To better assist in diagnosis this issue, can you provide the following:
- A reproducible test case, either a live web page or a JSFiddle.
- What browser and android versions? 
- Are you using react or just cloudinary-core? What are the package versions?

**Comment by AdamTyler** [comment] 2019-04-29 19:59
Unfortunately I'm not able to nail down the actual case that is producing this error, it just comes through our error tracker (Honey Badger).
Most of the errors are happening on Android Samsung Browser 9.2, but we are also seeing them on Chrome Chrome 64/65 Windows and Mac.
Here is a stack trace as far back as I can get it:
```
node_modules/cloudinary-core/cloudinary-core.js:5810:0:in `opener'
node_modules/cloudinary-core/cloudinary-core.js:5938:0:in `getStyles'
node_modules/cloudinary-core/cloudinary-core.js:5968:0:in `getWidthOrHeight'
node_modules/cloudinary-react/lib/components/Image/Image.js:202:0:in `width'
node_modules/cloudinary-react/lib/components/Image/Image.js:302:0:in `findContainerWidth'
node_modules/cloudinary-react/lib/components/Image/Image.js:110:0:in `cloudinary_update'
node_modules/cloudinary-react/lib/components/Image/Image.js:82:0:in `prepareState'
node_modules/react-dom/cjs/react-dom.production.min.js:133:31:in `componentWillReceiveProps'
node_modules/react-dom/cjs/react-dom.production.min.js:170:0:in `wf'
node_modules/react-dom/cjs/react-dom.production.min.js:180:0:in `Og'
```

**Comment by roeeba** [comment] 2020-02-17 12:25
Hi @AdamTyler, I apologize for the very late response. If this is still relevant, please share a reproducible test case, either a live web page or a JSFiddle, so we can further investigate it. Thanks!

**Comment by roeeba** [comment] 2020-07-16 07:57
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2020-07-16 07:57 UTC
Labels: question
