### ISSUE TITLE
Default image when no PublicID available?

### ISSUE THREAD

**Issue by texaspacm** [cloudinary/cloudinary-react#3] opened 2016-11-22 20:33 UTC
I'm using the <image> component in a list, and there may or may not be an image in cloudinary associated with the public ID i'm adding to the component.  

Any ideas on how to display a default image instead of showing a broken image on the page.  

Thanks

**Comment by mvanlonden** [comment] 2017-05-23 00:26
Any updates here? Also running into the same problem

**Comment by eitanp461** [comment] 2017-05-23 05:53
@mvanlonden @texaspacm an `onError` listener can help here:

```
          <cloudinaryReact.Image publicId="samplez"
            onError={() => {this.img.element.src='http://www.hardwickagriculture.org/blog/wp-content/uploads/placeholder.jpg'}}
            ref={(img) => { this.img = img; }}>
            <cloudinaryReact.Transformation width="200" crop="scale" angle="10"/>
          </cloudinaryReact.Image>
```

See example here - https://codepen.io/eitanp461/project/editor/ANWPqL/

**Comment by mvanlonden** [comment] 2017-05-23 19:04
Thanks, this works as a placeholder, but what I'm really looking for is a way for the component not to render the image tag until it has fetched the image. It seems like the `<img />` tag is rendered before the src attribute is added. This might be because I'm using the `responsive` attribute with auto width and the cloudinary-react needs to know the size of the image before fetching?

**Comment by eitanp461** [comment] 2017-05-24 08:54
@mvanlonden Please add more details regarding your use case.
Are you using server side rendering?
Can you update the CodePen with a reproduction?

**Comment by mvanlonden** [comment] 2017-05-24 19:07
Hmm after fiddling around for an hour or two I still can't reproduce it 😕. Although I have been able to fix it by messing with src directly in my project. [PR that fixes my issue](https://github.com/cloudinary/cloudinary-react/pull/18)

**Comment by roeeba** [comment] 2020-02-05 06:58
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2020-02-05 06:58 UTC
Labels: question
