### ISSUE TITLE
Breakpoint steps is not working

### ISSUE THREAD

**Issue by konrad147** [cloudinary/cloudinary-react#51] opened 2018-04-19 12:12 UTC
I have a component like this:
```jsx
<Image
  cloudName="cloud"
  dpr="auto"
  responsive
  width="auto"
  crop="scale"
  publicId={photoId}
/>
```
`Cloudinary JS SDK` by default use breakpoint steps value = 100, which means I do not make requests for images sizes like 124px, 223px and so on. Using `Image` component it is no longer true. It always gets the exact width of the container. 
I tried to set `responsiveUseBreakpoints` flag on `CloudinaryContext` element but with no effect.
What I discovered in `Image.js` component is that the `options.responsive_use_breakpoints` cannot be true, becasuse `options` object passed from `cloudinary_update` can contain only `breakpoints` and `responsive` props.

**Comment by strausr** [comment] 2018-04-30 09:10
@konrad147 Please note that the breakpoints are set by the size of the parent container. 

For example, 

`
<div className="imageContainer"> 
    <Image
        cloudName="<cloudname>"
	responsive
	width="auto"
	crop="scale"
	publicId={this.state.publicId}
     />
</div>

.imageContainer {
	width: 80vw;
}
`

If you want to set breakpoints, then the following will round up to the upper limit-

`
<div className="imageContainer"> 
    <Image
        cloudName="<cloudname>"
	crop="scale" 
        width="auto"
        responsive
        responsive_use_breakpoints
        breakpoints='250,500,750,1000,1250'
	publicId={this.state.publicId}
     />
</div>
`

**Comment by konrad147** [comment] 2018-05-07 07:31
@strausr Ok, `responsive_use_breakpoints` works with `Image` tag, but it does not work with `CloudinaryContext`, because `CloudinaryContext` expects `responsiveUseBreakpoints` property (which is not valid in the breakpoints checking code).
Moreover using `breakpoints` property on the `Image` tag throws error because it renders `img` tag with `breakpoints` attribute which is invalid in that place.

**Comment by strausr** [comment] 2018-05-08 08:43
@konrad147 We're unable to reproduce the above. Can you please elaborate on what you're trying to achieve?

**Comment by roeeba** [comment] 2018-09-13 09:46
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by maoznir** [comment] 2019-07-24 15:50
Hi @konrad147,
I've looked at this again and indeed as you described passing responsive_use_breakpoints to cloudinaryContext does not work.
I saw that you created a pr, will handle it.
Thanks

**Closed by maoznir** 2019-07-24 15:50 UTC
Labels: question
