### ISSUE TITLE
Illegal Invocation of requestAnimationFrame

### ISSUE THREAD

**Issue by Boughtmanatee5** [cloudinary/cloudinary-react#22] opened 2017-07-13 17:05 UTC
I've noticed in chrome 59 that requestAnimationFrame used in the handleResize method of the Image component throws an illegal invocation error.

```javascript
handleResize(e) {
  if (this.rqf) return;
  this.rqf = requestAnimationFrame(() => {
    this.rqf = null;
    let newState = this.prepareState();
    if(!Util.isEmpty(newState.url)) {
      this.setState(newState);
    }
  });
}
```

I believe this is because the native requestAnimationFrame is behind assigned to a custom object when exported.

I've tried using bind and call but they break the tests.

Has anyone else noticed this?

**Comment by creimers** [comment] 2017-07-14 13:29
@Boughtmanatee5 Yes, I have noticed this too.

<img width="1492" alt="bildschirmfoto 2017-07-14 um 15 28 30" src="https://user-images.githubusercontent.com/6090492/28214085-2b0b7392-68a9-11e7-8f82-02699aaeb390.png">

**Comment by eitanp461** [comment] 2017-07-16 20:35
@Boughtmanatee5 Can you provide a test case that reproduces the error?
You can fork this plunker - https://plnkr.co/edit/A3RpWXpNXth9cbt9EUDm?p=preview

**Comment by Boughtmanatee5** [comment] 2017-07-17 15:02
@eitanp461 I wasn't able to reproduce the issue in plunker. I was using [react-lazyload](https://www.npmjs.com/package/react-lazyload) in my project and switched to [react-lazy-load](https://www.npmjs.com/package/react-lazy-load) that resolved the illegal invocation. react-lazyload must change the content child components execute in somehow. I'll investigage and push an example later today.

**Comment by strausr** [comment] 2017-09-26 09:54
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by strausr** 2017-09-26 09:54 UTC
Labels: question
