### ISSUE TITLE
upload widget v2 bugs

### ISSUE THREAD

**Issue by mikestaub** [cloudinary/cloudinary-react#80] opened 2019-02-24 23:12 UTC
I noticed when using the upload widget that the tags I set in the options are not always set. I am generating a signature on my server with the params given by the uploadSignature() option. Sometimes those params are missing the tags or context, so when the POST request is sent using the signature I get a 401. This problem is intermittent.

Is the upload widget code open source? Where do we submit issues for it?

**Comment by aditimadan-Cloudinary** [comment] 2019-02-25 21:40
Can you please raise a support ticket here: https://support.cloudinary.com/hc/en-us/requests/new with your cloud name, code and the parameters you passed in order to reproduce the issue.

**Comment by roeeba** [comment] 2020-02-17 10:40
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2020-02-17 10:40 UTC
